### PR TITLE
feat: export assertVersionBump and publish for programatically usage

### PR DESCRIPTION
**Pull request by rodrigo4244**

### CODE REVIEW

**Comment by keenahn** [comment]
@rodrigo4244 hey. I would take the opposite approach. Make `assertVersionBump` and `publish` functions in `index.js` and have the `bin` files call those functions. 

The functions should not do console.log or process.exit, the bin files should.

**Comment by keenahn** [comment]
Coo. There's one more thing I thought of, which might be for this or another PR, but you should detect if `~/.npmrc` already exists and throw an error so that you don't overwrite it.

**Comment by rodrigo4244** [comment]
Cool! I can do that, but I believe that would be better in another PR!

**Comment by rodrigo4244** [comment]
I will make the PR for checking `~/.npmrc` files on top of this one and send for you to review!

**Pull request merged**
